module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: null
cabal-file: project.cabal
modules:
  Solar.Caster.Server:
    filename: Solar/Caster/Server.hs
  Solar.Caster.Channel:
    filename: Solar/Caster/Channel.hs
  Solar.Caster.Event:
    filename: Solar/Caster/Event.hs
  Solar.Utility.Wait:
    filename: Solar/Utility/Wait.hs
  Solar.Caster.Client:
    filename: Solar/Caster/Client.hs
  Solar.Caster.Time:
    filename: Solar/Caster/Time.hs
  Solar.Caster:
    filename: Solar/Caster.hs
  Solar.Utility.Date:
    filename: Solar/Utility/Date.hs
  Solar.Utility.Delta:
    filename: Solar/Utility/Delta.hs
version: 1
ghc-args: []
