module-template: ''
extensions: {}
environment: ghc-7.4.2-unstable
cabal-file: 'solar-dial.cabal'
modules:
  Test.Time:
    filename: tests/Test/Time.hs
  Test.Delta:
    filename: tests/Test/Delta.hs
  Main:
    filename: tests/Main.hs
  Solar.Cast.Internal.Time:
    filename: Solar/Dial/Internal/Time.hs
  Solar.Cast.Time:
    filename: Solar/Dial/Time.hs
  Solar.Dial.Delta:
    filename: Solar/Dial/Delta.hs
  Solar.Dial.Wait:
    filename: Solar/Dial/Wait.hs
version: 1
extra-packages: ! 'Hackage: tasty

  Hackage: tasty-hunit

  Git: https://github.com/feuerbach/tasty 791cbefbf8ca531b3b27cb07809a04581d38e1c9
  quickcheck'
ghc-args: []
